<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "szag_orangemap"
 *
 * Auto generated by Extension Builder 2017-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SZAG Orangemap',
	'description' => 'Map with filter options via dropdowns & ajax refresh',
	'category' => 'plugin',
	'author' => 'Thorsten Hoeke',
	'author_email' => 'hoeke@pierraa-group.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);